#!/usr/bin/env bash

export CONTECO_LABEL="module.streamsets - ContEco"
export CONTECO_DESCRIPTION="Streamsets module with managed standard URL UI."

export CONTECO_TYPE="module"
export CONTECO_NAME="streamsets"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
